version: '3'

services:
  mdcs:
    build: ./web
    restart: always
    ports:
      - "8000"
    depends_on:
      - mongo
      - redis
      - psql
    volumes:
      - ./settings.py:/srv/mgi-mdcs/mdcs/settings.py
      - ./xsd_registrator.py:/srv/mgi-mdcs/xsd_registrator.py
      - ./xsd_flattener_file.py:/srv/mgi-mdcs/xsd_flattener_file.py
    environment:
      - DJANGO_SETTINGS_MODULE=mdcs.settings
    networks:
      mdcs_network:
        aliases:
          - mdcs.svc      

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      mdcs_network:
        aliases:
          - nginx.svc
  
  mongo:
    image: mongo:3.4
    restart: always
    ports:
      - "27017"
    volumes:
      - mongo-data:/data/db/
      - ./db/set_mongodb_password.sh:/set_mongodb_password.sh
    environment:
      - MONGODB_ADMIN=admin
      - MONGODB_ADMIN_PASS=admin
      - MONGODB_USER=mgi_user
      - MONGODB_PASSWORD=mgi_password
    networks:
      mdcs_network:
        aliases:
          - mongo.svc

  mongo_client:
    image: mongo:3.4
    depends_on: 
      - mongo
    ports:
      - "27017"
    volumes:
      - ./db/set_mongodb_password.sh:/set_mongodb_password.sh
    entrypoint: []
    command: bash -c "/set_mongodb_password.sh"
    networks:
      mdcs_network:
        aliases:
          - mongo_client.svc

  redis:
    image: redis:5
    restart: always
    ports:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      mdcs_network:
        aliases:
          - redis.svc
   
  psql:
    image: postgres:latest
    restart: always
    ports:
      - "5432"
    volumes:
      - psql-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mgi_user
      - POSTGRES_PASSWORD=mgi_password
      - POSTGRES_DB=mgi
    networks:
      mdcs_network:
        aliases:
          - psql.svc

volumes:
  mongo-data:
  redis-data:
  psql-data:

networks:
  mdcs_network:
    driver: bridge    
