version: '3'

services:
  mdcs:
    build: ./web
    restart: always
    ports:
      - "8000"
    container_name: mdcs
    depends_on:
      - db
      - redis
    volumes:
      - ./settings.py:/srv/mgi-mdcs/mdcs/settings.py
    environment:
      - DJANGO_SETTINGS_MODULE=mdcs.settings
      
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  db:
    image: mongo:3.4
    restart: always
    container_name: db_mongo
    ports:
      - "27017"
    volumes:
      - mongo-data:/data/db/
      - ./db/set_mongodb_password.sh:/set_mongodb_password.sh
    environment:
      - MONGODB_ADMIN=admin
      - MONGODB_ADMIN_PASS=admin
      - MONGODB_USER=mgi_user
      - MONGODB_PASSWORD=mgi_password
  
  redis:
    image: redis:5
    restart: always
    container_name: redis
    ports:
      - "6379"
    volumes:
      - ./redis/data:/data

volumes:
  mongo-data:
  pg-data:

networks:
  mdcs_network:
    driver: bridge    
