web:
  build: ./web
  restart: always
  container_name: mdcs
  links:
    - db
    - redis
    - postgres
  volumes:
    - ./settings.py:/srv/mgi-mdcs/mgi/settings.py  
    - /srv/mgi-mdcs/
  environment:
    - DJANGO_SETTINGS_MODULE=mgi.settings
    
postgres:
  image: postgres:latest
  restart: always
  container_name: postgres
  ports:
    - "5432:5432"
  volumes:
    - ./postgres/pgdata:/var/lib/postgresql/data/
  environment:
    - POSTGRES_USER=mgiUser
    - POSTGRES_PASSWORD=pass4mgiUser123
    - POSTGRES_DB=mgi

nginx:
  image: nginx:latest
  restart: always
  container_name: nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - web
  volumes_from:
    - web
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

db:
  image: mongo:latest
  restart: always
  container_name: db_mongo
  ports:
    - "27017:27017"
  volumes:
    - ./db/data/db/:/data/db/
    - ./db/set_mongodb_password.sh:/set_mongodb_password.sh
  environment:
    - MONGODB_ADMIN=admin
    - MONGODB_ADMIN_PASS=admin
    - MONGODB_MGI=mgi_user
    - MONGODB_MGI_PASS=mgi_password

redis:
  image: redis:latest
  restart: always
  container_name: redis
  ports:
    - "6379:6379"
  volumes:
    - ./redis/data:/data